using System;

namespace YahooWeatherParser
{
	public enum ConditionCode : uint
	{
		Tornado = 0,
		TropicalStorm = 1,
		Hurricane = 2,
		SevereThunderstorms = 3,
		Thunderstorms = 4,
		MixedRainAndSnow = 5,
		MixedRainAndSleet = 6,
		MixedSnowAndSleet = 7,
		FreezingDrizzle = 8,
		Drizzle = 9,
		FreezingRain = 10,
		Showers = 11,
		ShowersConditionTwo = 12,
		SnowFlurries = 13,
		LightSnowShowers = 14,
		BlowingSnow = 15,
		Snow = 16,
		Hail = 17,
		Sleet = 18,
		Dust = 19,
		Foggy = 20,
		Haze = 21,
		Smoky = 22,
		Blustery = 23,
		Windy = 24,
		Cold = 25,
		Cloudy = 26,
		MostlyCloudyAtNight = 27,
		MostlyCloudyAtDay = 28,
		PartlyCloudyAtNight = 29,
		PartlyCloudyAtDay = 30,
		ClearAtNight = 31,
		Sunny = 32,
		FairAtNight = 33,
		FairAtDay = 34,
		MixedRainAndHail = 35,
		Hot = 36,
		IsolatedThunderstorms = 37,
		ScatteredThunderstorms = 38,
		ScatteredThunderstormsConditionTwo = 39,
		ScatteredShowers = 40,
		HeavySnow = 41,
		ScatteredSnowShowers = 42,
		HeavySnowConditionTwo = 43,
		PartlyCloudy = 44,
		Thundershowers = 45,
		SnowShowers = 46,
		IsolatedThundershowers = 47,
		NotAvailable = 3200
	}
}

